"""Generates ``README_dataset.md``: the data dictionary, the applicability matrix, and
the defect registry with expected findings — the answer key."""

from __future__ import annotations

from pathlib import Path

import polars as pl

# The answer key. Each entry: what was injected, where to find it, and what a competent
# analyst should conclude.
DEFECT_REGISTRY = [
    {
        "id": 1, "key": "unmapped_accounts",
        "what": "3 local accounts missing from map_local_to_group for 2 months, then fixed",
        "where": "map_local_to_group (absent rows); group revenue understated in those months",
        "expected_finding": "Group revenue understated then restated; the local trial balance never changes",
    },
    {
        "id": 2, "key": "ic_mismatch",
        "what": "One DE->ES goods transaction booked 1.3% lower by the buyer (timing: seller P06, buyer P07)",
        "where": "fact_gl where ic_flow='GOODS_DE_ES'; the two legs of one ic_txn_id",
        "expected_finding": "Exactly one IC transaction fails the net-to-zero check, by exactly 1.3%",
    },
    {
        "id": 3, "key": "ic_missing_partner_tag",
        "what": "One UK purchase from DE loses its ic_partner tag",
        "where": "fact_gl, ic_flow='GOODS_DE_UK', period 9: ic_partner is '~NA~' on the buyer leg",
        "expected_finding": "The row escapes automatic elimination; group COGS is overstated by that amount",
    },
    {
        "id": 4, "key": "topside_unreconciled",
        "what": "A group legal provision that exists ONLY at GRP and was never pushed to any local ledger",
        "where": "fact_topside where pushed_to_local = false",
        "expected_finding": "Sum of local ledgers never reconciles to GRP by this amount, in every period after it",
    },
    {
        "id": 5, "key": "cc_reorg_midyear",
        "what": "DE01 merges Brand + Digital marketing departments from FY25",
        "where": "dim_cost_center_version where is_restated = true",
        "expected_finding": "YoY department comparison breaks unless the version table is used to restate",
    },
    {
        "id": 6, "key": "allocation_rule_change",
        "what": "HQ-G&A allocates on revenue share in ACT but on headcount in BUD",
        "where": "allocation_rules: driver_actual vs driver_budget differ",
        "expected_finding": "An allocation-methodology variance that no price or volume explanation covers",
    },
    {
        "id": 7, "key": "mapping_drift_uk",
        "what": "UK direct management mapping disagrees with the chained mapping for 2 accounts",
        "where": "map_management vs map_local_to_group -> map_management",
        "expected_finding": "Two routes to the same management line give different answers",
    },
    {
        "id": 8, "key": "dormant_accounts",
        "what": "~15 accounts whose history goes to zero; one is COVID-named",
        "where": "fact_gl: accounts with activity that stops",
        "expected_finding": "Naive 'active accounts' lists are wrong; period-over-period completeness checks fire",
    },
    {
        "id": 9, "key": "late_period13_adjustments",
        "what": "Close adjustments posted to P13 rather than a month",
        "where": "fact_gl where is_period13 = true; dim_calendar period_no = 13",
        "expected_finding": "Any 12-month sum misses them; only FY totals are right",
    },
    {
        "id": 10, "key": "sku_relaunch_new_code",
        "what": "A SKU relaunched under a new code",
        "where": "dim_product_node: successor chains",
        "expected_finding": "Like-for-like SKU trend is broken; the analyst must link old and new codes",
    },
    {
        "id": 11, "key": "unassigned_product_tags",
        "what": "~0.5% of revenue rows carry product = 'UNASSIGNED' instead of a real member",
        "where": "fact_gl and fact_sales_lines where product_node_id = 'UNASSIGNED'",
        "expected_finding": (
            "Revenue by product does not sum to total revenue. Critically, 'UNASSIGNED' is NOT "
            "the same as '~NA~': the latter means the dimension does not apply at all"
        ),
    },
    {
        "id": 12, "key": "subledger_reconciling_item",
        "what": "A manual GL correction that makes GL != sub-ledger for one month",
        "where": "fact_gl, source = 'manual_correction'",
        "expected_finding": "V7 fails for exactly one entity/month by a documented amount",
    },
]


def write_dataset_readme(dataset, report, output_dir: Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "README_dataset.md"
    cfg = dataset.config

    lines: list[str] = []
    add = lines.append

    add("# Volteo Electronics Group — synthetic finance dataset")
    add("")
    add(f"Generated by `volteogen` with seed `{cfg.seed}`, preset `{cfg.get('scale_preset')}`, "
        f"industry pack `{cfg.industry_pack}`.")
    add("")
    add("Deterministic: the same seed and config reproduce this dataset exactly.")
    add("")

    add("## What makes this dataset hard (on purpose)")
    add("")
    add("1. **Weighted roll-ups.** 61 of the 531 US-GAAP calculation arcs carry weight −1. "
        "`SUM(amount)` over the GAAP tree returns a plausible, wrong number; you must use "
        "`SUM(amount × weight_product)`.")
    add("2. **Three dimension states.** `~NA~` means the dimension structurally does not "
        "apply (payroll has no product). `UNASSIGNED` means it should have been tagged and "
        "was not — a defect. A real member means tagged. Conflating the first two is the "
        "easiest way to get a wrong answer.")
    add("3. **Different grains.** SKU and customer detail exist ONLY in `fact_sales_lines`. "
        "`fact_gl` is monthly trial-balance grain and carries product at FAMILY level. "
        "COGS variances carry no product at all — they post at plant level and are "
        "genuinely unallocatable.")
    add("4. **Meaning encoded in local account numbers.** DE01 splits revenue by VAT rate "
        "(8400 = 19%, 8300 = 7%), ES01 splits it by geography (7000 domestic / 7001 "
        "intra-community / 7002 export), UK01 encodes neither. So 'export revenue' is "
        "answerable two different ways that must agree.")
    add("5. **Charts of different depth.** Business Central nests six levels, SKR03 and PGC "
        "four, Sage two. Level-based logic breaks by design; use `node_type`, not depth.")
    add("6. **Non-calendar fiscal year.** P01 is July, so the Christmas peak sits at P05/P06 "
        "mid-year, and P13 is a real posting period that no 12-month sum will include.")
    add("7. **Mid-history acquisition.** UK01 enters consolidation part-way through, creating "
        "a genuine M&A scope effect in group growth.")
    add("")

    add("## Tables")
    add("")
    add("| table | rows | columns |")
    add("|---|---:|---:|")
    for row in dataset.summary().to_dicts():
        add(f"| `{row['table']}` | {row['rows']:,} | {row['columns']} |")
    add("")

    add("## Dimensional applicability matrix")
    add("")
    add("Both the generator and the validator read this table, so the rule is stated once. "
        "`na` -> the cell contains `~NA~`; `applicable`/`mandatory` -> a real member is "
        "required; `conditional_*` -> a member only when the condition holds.")
    add("")
    matrix = dataset["meta_account_dimensionality"]
    header = ["account_class", "product", "market", "customer", "cost_center", "ic_partner",
              "gl_product_grain", "subledger_product_grain"]
    add("| " + " | ".join(header) + " |")
    add("|" + "---|" * len(header))
    for row in matrix.to_dicts():
        add("| " + " | ".join(str(row.get(h, "")) for h in header) + " |")
    add("")

    add("## Validation results")
    add("")
    add("`EXPECTED-FAIL` means a registered defect reproduced exactly as documented — that "
        "is a pass, not a problem.")
    add("")
    add("| check | name | status | detail |")
    add("|---|---|---|---|")
    for row in report.frame().to_dicts():
        add(f"| {row['check']} | {row['name']} | **{row['status']}** | {row['detail']} |")
    add("")

    add("## Defect registry — the answer key")
    add("")
    add("Each defect is individually toggleable in `config/default.yaml` under `defects:`.")
    add("")
    # Report what the build ACTUALLY injected, taken from the injector log, so the
    # answer key can never drift from the data it documents.
    injected = {}
    if "meta_defects_injected" in dataset.tables:
        frame = dataset["meta_defects_injected"]
        if frame.height and "defect" in frame.columns:
            injected = {row["defect"]: row for row in frame.to_dicts()}

    engine_backed = {
        "ic_mismatch": "asserted by validator V4 as an EXPECTED-FAIL",
        "ic_missing_partner_tag": "visible in v_data_quality",
        "topside_unreconciled": "fact_topside where pushed_to_local = false",
        "cc_reorg_midyear": "dim_cost_center_version where is_restated",
        "allocation_rule_change": "allocation_rules: driver_actual vs driver_budget",
        "unassigned_product_tags": "counted by validator V8",
        "late_period13_adjustments": "fact_gl where is_period13",
    }

    for defect in DEFECT_REGISTRY:
        key = defect["key"]
        enabled = cfg.defect_enabled(key)
        add(f"### {defect['id']}. `{key}` — {'ON' if enabled else 'off'} in config")
        add("")
        add(f"- **What:** {defect['what']}")
        add(f"- **Where to find it:** {defect['where']}")
        add(f"- **Expected finding:** {defect['expected_finding']}")
        if key in injected:
            row = injected[key]
            detail = row.get("detail") or ""
            accounts = row.get("accounts") or ""
            add(f"- **Injected in this build:** {accounts}{' — ' if accounts and detail else ''}{detail}")
        elif enabled and key in engine_backed:
            add(f"- **Injected in this build:** yes — {engine_backed[key]}")
        elif enabled:
            add("- **Injected in this build:** enabled but produced no rows in this run")
        else:
            add("- **Injected in this build:** no (toggled off)")
        add("")

    add("## Financial narrative")
    add("")
    add("Sign and trend are configured, not emergent. The calibrator scales only "
        "discretionary baselines (standard-cost ratio, opex level) by a single factor per "
        "entity and fiscal year, so seasonality, noise and launch ramps are preserved exactly.")
    add("")
    if "meta_calibration" in dataset.tables:
        add("| entity | FY | arc | GM target | GM actual | NI target | NI actual |")
        add("|---|---:|---|---:|---:|---:|---:|")
        for row in dataset["meta_calibration"].to_dicts():
            add(f"| {row['entity']} | {row['fiscal_year']} | {row['arc']} | "
                f"{row['gm_target']:.3f} | {row['gm_actual']:.3f} | "
                f"{row['ni_target']:.3f} | {row['ni_actual']:.3f} |")
        add("")

    add("## Hierarchy irregularity (validator V11)")
    add("")
    add("The build FAILS if a generated hierarchy comes out regular.")
    add("")
    if "meta_hierarchy_irregularity" in dataset.tables:
        add("| dim | nodes | leaves | leaf depth | sibling fan-out | skip-level branches |")
        add("|---|---:|---:|---|---|---:|")
        for row in dataset["meta_hierarchy_irregularity"].to_dicts():
            add(f"| {row['dim']} | {row['nodes']} | {row['leaves']} | "
                f"{row['min_leaf_depth']}–{row['max_leaf_depth']} | "
                f"{row['min_siblings']}–{row['max_siblings']} | {row['skip_level_branches']} |")
        add("")

    add("## Seed provenance")
    add("")
    add("No chart of accounts or taxonomy structure is invented. See `seeds/SOURCES.md` "
        "for upstream URLs, licences and pinned checksums.")
    add("")
    if dataset.seeds is not None:
        add("| chart | nodes | posting accounts | max depth |")
        add("|---|---:|---:|---:|")
        for row in dataset.seeds.summary().to_dicts():
            add(f"| {row['coa_id']} | {row['nodes']} | {row['postings']} | {row['max_depth']} |")
        add("")

    if dataset.notes:
        add("## Build notes")
        add("")
        for note in dataset.notes:
            add(f"- {note}")
        add("")

    path.write_text("\n".join(lines))
    return path
