"""
UK Chart of Accounts - nominal code data.

Written from scratch based on the standard UK nominal code structure
used by Sage, Xero, FreeAgent, and other UK accounting software.
This is publicly available reference data, not proprietary.

VAT treatments verified against HMRC guidance. HMRC box mappings
reference CT600, VAT Return, FPS/RTI, EPS, CIS, and P11D forms.
"""

from .enums import AccountType as T, VatRate as V
from .models import Account

# fmt: off
ACCOUNTS: tuple[Account, ...] = (

    # ── Fixed Assets (10-51) ─────────────────────────────────────────
    Account(10,   "Freehold Property",              T.FIXED_ASSET,  V.STANDARD,      tags=("property",),
            description="New commercial property (under 3 years) is standard rated. Older property is exempt unless the seller has opted to tax. Residential property is exempt."),
    Account(11,   "Leasehold Property",             T.FIXED_ASSET,  V.STANDARD,      tags=("property",),
            description="Commercial lease premiums are standard rated. Residential leases are exempt. The grant of a new commercial lease is a standard-rated supply."),
    Account(20,   "Plant and Machinery",            T.FIXED_ASSET,  V.STANDARD,      tags=("capital",),
            description="VAT reclaimable on purchase. Claim capital allowances (Annual Investment Allowance) instead of depreciation for tax relief."),
    Account(21,   "Plant/Machinery Depreciation",   T.FIXED_ASSET,  V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Depreciation is disallowable for corporation tax. Add back on CT600 and claim capital allowances instead."),
    Account(30,   "Office Equipment",               T.FIXED_ASSET,  V.STANDARD,      tags=("capital",),
            description="Computers, printers, phones etc. VAT reclaimable on purchase. Eligible for Annual Investment Allowance."),
    Account(31,   "Office Equipment Depreciation",  T.FIXED_ASSET,  V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Disallowable for corporation tax. Add back on CT600."),
    Account(40,   "Furniture and Fixtures",         T.FIXED_ASSET,  V.STANDARD,      tags=("capital",),
            description="Desks, chairs, shelving, fittings. VAT reclaimable. Eligible for Annual Investment Allowance."),
    Account(41,   "Furniture/Fixture Depreciation",  T.FIXED_ASSET,  V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Disallowable for corporation tax. Add back on CT600."),
    Account(50,   "Motor Vehicles",                 T.FIXED_ASSET,  V.STANDARD,      tags=("capital", "motor"),
            description="Company cars are a reportable benefit in kind on form P11D Section A-F."),
    Account(51,   "Motor Vehicles Depreciation",    T.FIXED_ASSET,  V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation", "motor"),
            description="Disallowable for corporation tax. Add back on CT600. Claim capital allowances based on CO2 emissions instead."),

    # ── Current Assets (1001-1250) ───────────────────────────────────
    Account(1001, "Stock",                          T.CURRENT_ASSET, V.STANDARD,
            description="Closing stock valuation at lower of cost or net realisable value. VAT on stock purchases is reclaimable when purchased, not when sold."),
    Account(1002, "Work in Progress",               T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Partially completed goods or services. Valued at cost of materials, labour, and attributable overheads. No VAT until supply is complete."),
    Account(1003, "Finished Goods",                 T.CURRENT_ASSET, V.STANDARD,
            description="Completed products awaiting sale. Valued at the lower of cost and net realisable value (FRS 102 Section 13). Input VAT was reclaimed on the materials when purchased."),
    Account(1004, "Raw Materials",                  T.CURRENT_ASSET, V.STANDARD,
            description="Unprocessed inputs held for production. Part of closing stock at the lower of cost and net realisable value. Input VAT reclaimable on purchase, not on consumption."),
    Account(1100, "Debtors Control Account",        T.CURRENT_ASSET, V.OUTSIDE_SCOPE, tags=("control",),
            description="Total trade debtors balance. Outside scope as this is a control account — VAT is accounted for on individual sales invoices."),
    Account(1101, "Sundry Debtors",                 T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Miscellaneous one-off debtor balances that do not belong in the main sales ledger. Outside scope — VAT is recorded on the originating transaction, not the debtor balance."),
    Account(1102, "Other Debtors",                  T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Non-trade receivables such as staff advances, VAT or tax refunds due, or rent deposits. Outside scope of VAT as these are not supplies of goods or services."),
    Account(1103, "Prepayments",                    T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Expenses paid in advance (e.g. annual insurance, rent paid quarterly). Release to the relevant expense account in the period they relate to."),
    Account(1104, "Inter-company Debtors",          T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Amounts receivable from group or related companies. Eliminated on consolidation. Inter-company charges for goods or services should still carry VAT where both parties are separately VAT-registered."),
    Account(1105, "Provision for Credit Notes",     T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Estimate of credit notes likely to be raised against outstanding sales (returns, disputes, price adjustments). Held as a contra to debtors and released when the actual credit note is issued."),
    Account(1106, "Provision for Doubtful Debts",   T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Estimate of debts unlikely to be collected. Tax relief available when debts are actually written off, not when provisioned."),
    Account(1200, "Bank Current Account",           T.CURRENT_ASSET, V.OUTSIDE_SCOPE, tags=("bank",),
            description="Main business current account. Bank transactions are outside scope — VAT is on the underlying purchase or sale, not the bank movement."),
    Account(1210, "Bank Deposit Account",           T.CURRENT_ASSET, V.OUTSIDE_SCOPE, tags=("bank",),
            description="Business savings or deposit account for surplus cash. Interest earned is VAT exempt and booked separately as finance income. Movements themselves are outside scope."),
    Account(1220, "Euro Bank Account",              T.CURRENT_ASSET, V.OUTSIDE_SCOPE, tags=("bank",),
            description="Foreign currency account. Revalue at year-end using HMRC exchange rates. Exchange gains/losses go to code 7906."),
    Account(1230, "Petty Cash",                     T.CURRENT_ASSET, V.OUTSIDE_SCOPE, tags=("cash",),
            description="Small cash fund for minor expenses. VAT is reclaimable on petty cash purchases if a valid VAT receipt is held."),
    Account(1235, "Cash Register",                  T.CURRENT_ASSET, V.OUTSIDE_SCOPE, tags=("cash",),
            description="Physical till or cash drawer holding retail takings. Reconcile daily against Z-reads and bank deposits. Outside scope — VAT is accounted for on each underlying sale, not the cash balance."),
    Account(1240, "Company Credit Card",            T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Credit card balance as an asset (amounts due to be repaid). VAT is on the individual purchases, not the card payment."),
    Account(1250, "Credit Card Receipts",           T.CURRENT_ASSET, V.OUTSIDE_SCOPE,
            description="Customer card payments in transit between the merchant acquirer and the bank (typically 1-3 working days). Outside scope — VAT is accounted for on the original sale, not on settlement timing."),

    # ── Current Liabilities (2100-2230) ──────────────────────────────
    Account(2100, "Creditors Control Account",      T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, tags=("control",),
            description="Total trade creditors balance. Control account — VAT is on individual purchase invoices, not the control total."),
    Account(2101, "Sundry Creditors",               T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE,
            description="Miscellaneous one-off creditor balances that do not belong in the main purchase ledger. Outside scope — VAT is on the originating invoice, not the creditor balance."),
    Account(2102, "Other Creditors",                T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE,
            description="Non-trade payables such as tax liabilities awaiting payment, director reimbursements, or refunds owed to customers. Outside scope as these are not supplies."),
    Account(2109, "Accruals",                       T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE,
            description="Expenses incurred but not yet invoiced (e.g. utility bills, audit fees). Reverse in the next period when the actual invoice arrives."),
    Account(2110, "Corporation Tax",                T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 86", tags=("tax", "hmrc"),
            description="Corporation tax liability for the current period. Due 9 months and 1 day after the accounting period end. Reported on CT600 Box 86."),
    Account(2200, "Sales Tax Control Account",      T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="VAT Return Box 1", tags=("vat", "control"),
            description="Output VAT collected on sales. Reported on VAT Return Box 1 (VAT due on sales)."),
    Account(2201, "Purchase Tax Control Account",   T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="VAT Return Box 4", tags=("vat", "control"),
            description="Input VAT paid on purchases. Reported on VAT Return Box 4 (VAT reclaimed on purchases)."),
    Account(2202, "VAT Liability",                  T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="VAT Return Box 5", tags=("vat", "hmrc"),
            description="Net VAT owed to (or due from) HMRC. Box 1 minus Box 4. Due by the 7th of the second month after the VAT quarter end (or 12th if paying by direct debit)."),
    Account(2204, "Manual Adjustments",             T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE,
            description="Manual VAT adjustments such as partial exemption corrections, capital goods scheme adjustments, or bad debt relief claims."),
    Account(2210, "P.A.Y.E.",                       T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll", "hmrc"),
            description="Income tax deducted from employee wages. Report via Full Payment Submission (FPS) to HMRC on or before each pay date. Pay monthly by the 22nd."),
    Account(2211, "National Insurance",             T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll", "hmrc"),
            description="Employee and employer NI contributions. Reported via FPS. Employer NI is an additional cost above the gross wage."),
    Account(2220, "Net Wages",                      T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Wages payable to employees after PAYE and NI deductions. The amount actually transferred to the employee's bank account."),
    Account(2230, "Pension Fund",                   T.CURRENT_LIABILITY, V.OUTSIDE_SCOPE, tags=("payroll",),
            description="Auto-enrolment pension contributions (employee + employer). Must be paid to the pension provider by the 22nd of the following month."),

    # ── Long-Term Liabilities (2300-2330) ────────────────────────────
    Account(2300, "Loans",                          T.LONG_TERM_LIABILITY, V.OUTSIDE_SCOPE,
            description="Bank loans and other borrowings. Interest is exempt from VAT. Capital repayments are outside scope."),
    Account(2301, "Directors Loan Account (Director 1)", T.LONG_TERM_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 79", tags=("directors",),
            description="Overdrawn DLA (company owes director or vice versa). If director owes the company more than 15,000 at year-end, S455 tax (33.75%) applies. Report on CT600 Box 79."),
    Account(2302, "Directors Loan Account (Director 2)", T.LONG_TERM_LIABILITY, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 79", tags=("directors",),
            description="Second director's loan account. Same S455 rules apply as Director 1."),
    Account(2310, "Hire Purchase",                  T.LONG_TERM_LIABILITY, V.OUTSIDE_SCOPE,
            description="HP agreements. VAT is reclaimable upfront on the full cash price (not the HP interest). Interest element is exempt."),
    Account(2330, "Mortgages",                      T.LONG_TERM_LIABILITY, V.OUTSIDE_SCOPE,
            description="Commercial property mortgages. Interest is exempt from VAT. Capital repayments are outside scope."),

    # ── Equity (3000-3200) ───────────────────────────────────────────
    Account(3000, "Ordinary Shares",                T.EQUITY, V.OUTSIDE_SCOPE,
            description="Share capital issued. Outside scope of VAT as issuing shares is not a supply of goods or services."),
    Account(3010, "Preference Shares",              T.EQUITY, V.OUTSIDE_SCOPE,
            description="Fixed-dividend shares. Preference shareholders are paid before ordinary shareholders but typically have no voting rights."),
    Account(3100, "Reserves",                       T.EQUITY, V.OUTSIDE_SCOPE,
            description="Retained earnings and other reserves. Distributable reserves can be used for dividend payments."),
    Account(3101, "Undistributed Reserves",         T.EQUITY, V.OUTSIDE_SCOPE,
            description="Reserves not yet allocated to a specific purpose (capital, revaluation, or distributable). Carried forward until appropriated or released back to profit and loss."),
    Account(3200, "Profit and Loss Account",        T.EQUITY, V.OUTSIDE_SCOPE,
            description="Cumulative retained profit or loss brought forward from prior years. Updated at each year-end."),

    # ── Income (4000-4905) ───────────────────────────────────────────
    Account(4000, "Sales Type A",                   T.INCOME, V.STANDARD, hmrc_box="CT600 Box 42; VAT Return Box 1, Box 6", tags=("sales",),
            description="Primary sales category. Rename to match your business (e.g. 'Product Sales', 'Consulting Revenue'). Standard rated unless selling zero-rated or exempt goods/services."),
    Account(4001, "Sales Type B",                   T.INCOME, V.STANDARD, hmrc_box="CT600 Box 42; VAT Return Box 1, Box 6", tags=("sales",),
            description="Secondary sales category. Use to separate revenue streams for reporting."),
    Account(4002, "Sales Type C",                   T.INCOME, V.STANDARD, hmrc_box="CT600 Box 42; VAT Return Box 1, Box 6", tags=("sales",),
            description="Tertiary sales category. Use alongside 4000-4001 to split revenue streams for reporting. Standard rated unless the underlying supply is zero-rated or exempt."),
    Account(4009, "Discounts Allowed",              T.INCOME, V.OUTSIDE_SCOPE, tags=("sales",),
            description="Trade or settlement discounts given to customers. Reduces turnover. Outside scope as it adjusts the original supply value."),
    Account(4010, "Management Charges Receivable",  T.INCOME, V.STANDARD, hmrc_box="CT600 Box 42",
            description="Inter-company management fees charged to group companies. Standard rated if between separate VAT-registered entities."),
    Account(4099, "Flat Rate - Benefit/Cost",       T.INCOME, V.OUTSIDE_SCOPE, tags=("vat",),
            description="Used by businesses on the VAT Flat Rate Scheme. Records the difference between flat rate VAT paid and actual VAT collected."),
    Account(4100, "Sales Type D",                   T.INCOME, V.STANDARD, hmrc_box="CT600 Box 42; VAT Return Box 1, Box 6", tags=("sales",),
            description="Additional sales category for businesses with more than three revenue streams. Rename to match your business (e.g. 'Export Sales', 'Online Store'). Standard rated by default."),
    Account(4101, "Sales Type E",                   T.INCOME, V.STANDARD, hmrc_box="CT600 Box 42; VAT Return Box 1, Box 6", tags=("sales",),
            description="Additional sales category. Use for finer-grained revenue tracking alongside 4000-4100. Standard rated unless the specific supply requires a different treatment."),
    Account(4200, "Sales of Assets",                T.INCOME, V.STANDARD, tags=("capital",),
            description="Proceeds from selling fixed assets. If the asset was claimed under capital allowances, a balancing charge or allowance may apply."),
    Account(4400, "Credit Charges (Late Payments)", T.INCOME, V.OUTSIDE_SCOPE,
            description="Statutory late payment interest under the Late Payment of Commercial Debts Act is compensatory damages, not a supply of finance. Outside the scope of VAT."),
    Account(4900, "Miscellaneous Income",           T.INCOME, V.STANDARD, hmrc_box="CT600 Box 43",
            description="Non-trading income that doesn't fit other categories. Reported separately from turnover on CT600 Box 43."),
    Account(4901, "Royalties Received",             T.INCOME, V.STANDARD, hmrc_box="CT600 Box 43",
            description="Licensing and royalty income. Standard rated for UK intellectual property. Withholding tax may apply on overseas royalties."),
    Account(4902, "Commissions Received",           T.INCOME, V.STANDARD, hmrc_box="CT600 Box 43",
            description="Commission income from referrals, introductions, or agency arrangements. Standard rated."),
    Account(4903, "Insurance Claims",               T.INCOME, V.OUTSIDE_SCOPE,
            description="Proceeds from insurance claims. Outside scope of VAT as insurance payouts are compensation, not a supply."),
    Account(4904, "Rent Income",                    T.INCOME, V.EXEMPT,  hmrc_box="CT600 Box 43; SA105", tags=("property",),
            description="Residential rental income is exempt. Commercial rental income is standard rated (20%) if the landlord has opted to tax the property."),
    Account(4905, "Distribution and Carriage",      T.INCOME, V.STANDARD,
            description="Delivery charges recharged to customers. Standard rated as part of the composite supply."),

    # ── Direct Expenses (5000-6900) ──────────────────────────────────
    Account(5000, "Materials Purchased",            T.DIRECT_EXPENSE, V.STANDARD, hmrc_box="VAT Return Box 4, Box 7", tags=("purchases",),
            description="Raw materials and goods for resale. Standard rated with VAT reclaimable. Reported on VAT Return Box 4 (input tax) and Box 7 (net purchases)."),
    Account(5001, "Materials Imported",             T.DIRECT_EXPENSE, V.STANDARD, hmrc_box="VAT Return Box 2, Box 4, Box 9", tags=("purchases",),
            description="EU acquisitions: VAT Return Box 2 (VAT due) and Box 9 (total value). Non-EU imports: postponed VAT accounting uses Box 1 and Box 4."),
    Account(5002, "Miscellaneous Purchases",        T.DIRECT_EXPENSE, V.STANDARD, hmrc_box="VAT Return Box 4, Box 7", tags=("purchases",),
            description="Direct cost purchases not fitting 5000/5001/5003. Standard rated. Reported on VAT Return Box 4 and Box 7. Keep usage minimal — prefer specific codes for clearer reporting."),
    Account(5003, "Packaging",                      T.DIRECT_EXPENSE, V.STANDARD, tags=("purchases",),
            description="Packaging materials used for goods sold (boxes, labels, bubble wrap, tape). Standard rated. VAT reclaimable as a direct cost of sale."),
    Account(5009, "Discounts Taken",                T.DIRECT_EXPENSE, V.OUTSIDE_SCOPE,
            description="Settlement or trade discounts received from suppliers. Outside scope as it adjusts the original supply value."),
    Account(6000, "Productive Labour",              T.DIRECT_EXPENSE, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Wages of employees directly involved in production or service delivery. Processed via PAYE (FPS/RTI). Part of cost of sales rather than overhead payroll."),
    Account(6001, "Cost of Sales Labour",           T.DIRECT_EXPENSE, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Wages attributable to cost of sales (e.g. site staff, fulfilment workers, production operatives). Processed via PAYE (FPS/RTI). Distinct from overhead staff salaries in 7003."),
    Account(6002, "Sub-Contractors",                T.DIRECT_EXPENSE, V.STANDARD, hmrc_box="CIS Monthly Return", tags=("cis",),
            description="Construction industry subcontractors: domestic reverse charge applies since March 2021. Customer accounts for VAT on qualifying CIS supplies."),
    Account(6100, "Sales Commissions",              T.DIRECT_EXPENSE, V.STANDARD,
            description="Commissions paid to sales agents or affiliates. Standard rated as a supply of services."),
    Account(6200, "Sales Promotions",               T.DIRECT_EXPENSE, V.STANDARD, tags=("marketing",),
            description="Promotional activities such as discounts, samples at events, and trade show stands. Standard rated. Distinct from gifts (6202) which have a 50 deemed-supply threshold."),
    Account(6201, "Advertising",                    T.DIRECT_EXPENSE, V.STANDARD, tags=("marketing",),
            description="Online and offline advertising costs. VAT reclaimable on UK advertising. Overseas advertising may be outside scope."),
    Account(6202, "Gifts and Samples",              T.DIRECT_EXPENSE, V.STANDARD, tags=("marketing",),
            description="Business gifts over 50 per recipient per year are treated as a deemed supply — output VAT must be accounted for. Under 50 is outside scope."),
    Account(6203, "P.R. (Literature & Brochures)",  T.DIRECT_EXPENSE, V.STANDARD, tags=("marketing",),
            description="Printed marketing materials — brochures, flyers, product sheets, corporate literature. Standard rated with VAT reclaimable."),
    Account(6900, "Miscellaneous Expenses",         T.DIRECT_EXPENSE, V.STANDARD,
            description="Direct cost expenses that do not fit elsewhere. Standard rated by default. Keep usage minimal — categorise to specific codes where possible for better reporting."),

    # ── Overheads (7000-8250) ────────────────────────────────────────
    # Payroll
    Account(7000, "Gross Wages",                    T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Total gross pay of employees before PAYE and NI deductions. Reported via Full Payment Submission (FPS) on or before each pay date. Outside scope — wages are not a supply of goods or services."),
    Account(7001, "Directors Salaries",             T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll", "directors"),
            description="Formal salary payments to company directors processed via PAYE. Reported on FPS. Directors use an annual earnings period for NI, distinct from ordinary employees."),
    Account(7002, "Directors Remuneration",         T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll", "directors"),
            description="Non-salary director compensation — bonuses, fees, and ex-gratia payments processed via PAYE. Use 7001 for regular salary. Dividends are equity distributions (reserves), not remuneration, and do not belong here."),
    Account(7003, "Staff Salaries",                 T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Monthly salaries of non-director employees. Processed via PAYE and reported on Full Payment Submission (FPS) on or before each pay date. Outside scope of VAT."),
    Account(7004, "Wages - Regular",                T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Weekly or hourly wages for regular employees processed via PAYE. Reported on FPS on or before each pay date. Outside scope of VAT."),
    Account(7005, "Wages - Casual",                 T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll",),
            description="Wages for casual, zero-hours, or short-term staff processed via PAYE. Still subject to auto-enrolment assessment if earnings exceed the qualifying threshold."),
    Account(7006, "Employers N.I. (Non-Directors)", T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI; EPS", tags=("payroll",),
            description="Employer's Class 1 secondary NI contributions on non-director wages. Reported via FPS. Eligible employers can offset against Employment Allowance (claimed on EPS)."),
    Account(7007, "Employers Pensions",             T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI", tags=("payroll", "pension"),
            description="Employer auto-enrolment pension contributions (minimum 3% of qualifying earnings). Must be paid to the scheme by the 22nd of the following month."),
    Account(7008, "Recruitment Expenses",           T.OVERHEAD, V.STANDARD, tags=("payroll",),
            description="Agency fees, job advertising, and recruitment platform subscriptions. Standard rated with VAT reclaimable on UK suppliers. Deductible in the period incurred."),
    Account(7009, "Adjustments",                    T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("payroll",),
            description="Payroll corrections and prior-period adjustments — under/over-accruals, reclassifications between pay codes, and corrections to earlier FPS submissions. Outside scope of VAT. Keep usage narrow to avoid masking errors."),
    Account(7010, "SSP Reclaimed",                  T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="EPS", tags=("payroll",),
            description="Legacy code — Statutory Sick Pay recovery via EPS. The Percentage Threshold Scheme ended April 2014 and COVID-era SSP rebates have also ended. Retained for historical records and the rare cases where recovery still applies."),
    Account(7011, "SMP Reclaimed",                  T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="EPS", tags=("payroll",),
            description="Statutory Maternity Pay recovered from HMRC via the Employer Payment Summary (EPS). Small employers reclaim 103%; larger employers reclaim 92%. Same mechanism applies to SPP, ShPP, and SAP."),
    Account(7012, "Employers N.I. (Directors)",     T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="FPS/RTI; EPS", tags=("payroll", "directors"),
            description="Employer's Class 1 secondary NI on director remuneration. Directors use an annual earnings period for NI (or the alternative method if elected), causing different in-year timing vs ordinary employees."),

    # Premises
    Account(7100, "Rent",                           T.OVERHEAD, V.EXEMPT,   tags=("premises",),
            description="Residential rent is exempt. Commercial rent on opted-in properties is standard rated (20%)."),
    Account(7102, "Water Rates",                    T.OVERHEAD, V.ZERO,     tags=("premises", "utilities"),
            description="Water supply and sewerage are zero-rated for VAT purposes."),
    Account(7103, "General Rates",                  T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("premises",),
            description="Business rates paid to the local authority. Outside scope of VAT as this is a tax, not a supply."),
    Account(7104, "Premises Insurance",             T.OVERHEAD, V.EXEMPT,   tags=("premises", "insurance"),
            description="Building and contents insurance. All insurance premiums are VAT exempt. Insurance Premium Tax (IPT) applies instead."),

    # Utilities
    Account(7200, "Electricity",                    T.OVERHEAD, V.STANDARD, tags=("utilities",),
            description="Business use is standard rated (20%). Domestic and charity use qualifies for the reduced rate (5%) with a supplier declaration."),
    Account(7201, "Gas",                            T.OVERHEAD, V.STANDARD, tags=("utilities",),
            description="Same VAT treatment as electricity. Business use at 20%, domestic/charity at 5% with supplier declaration."),
    Account(7202, "Oil",                            T.OVERHEAD, V.STANDARD, tags=("utilities",),
            description="Heating oil for business use is standard rated. Domestic/charity use qualifies for reduced rate (5%)."),
    Account(7203, "Other Heating Costs",            T.OVERHEAD, V.STANDARD, tags=("utilities",),
            description="Alternative heating fuels (wood pellets, LPG, coal) not covered by 7200-7202. Standard rated for business use. Domestic/charity use qualifies for the reduced rate (5%) with a supplier declaration."),

    # Motor
    Account(7300, "Vehicle Fuel",                   T.OVERHEAD, V.STANDARD, tags=("motor",),
            description="Company car fuel is a reportable benefit in kind (P11D Section M)."),
    Account(7301, "Vehicle Repairs and Servicing",  T.OVERHEAD, V.STANDARD, tags=("motor",),
            description="Routine servicing, MOTs, tyres, and repairs on business vehicles. Standard rated with VAT reclaimable on company-owned vehicles. Employees' personal vehicles claim via mileage (7306) instead."),
    Account(7302, "Vehicle Licences",               T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("motor",),
            description="Road tax (VED). Outside scope of VAT as this is a government duty."),
    Account(7303, "Vehicle Insurance",              T.OVERHEAD, V.EXEMPT,   tags=("motor", "insurance"),
            description="Motor insurance premiums. VAT exempt — Insurance Premium Tax applies instead."),
    Account(7304, "Miscellaneous Motor Expenses",   T.OVERHEAD, V.STANDARD, tags=("motor",),
            description="Parking, car wash, MOT, and other motor costs. VAT reclaimable where a valid VAT receipt is held."),
    Account(7305, "Congestion Charges",             T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("motor",),
            description="London congestion charge, ULEZ, and clean air zone charges. Outside scope as these are regulatory charges, not a supply."),
    Account(7306, "Mileage Claims",                 T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("motor",),
            description="Mileage allowances are outside scope, but businesses can reclaim VAT on the fuel element using HMRC advisory fuel rates via a separate VAT-only journal."),

    # Travel & Entertainment
    Account(7400, "Travelling",                     T.OVERHEAD, V.STANDARD, tags=("travel",),
            description="Business travel costs — train, bus, taxi, flights. UK rail and bus fares are zero-rated; taxis and flights are standard rated."),
    Account(7401, "Car Hire",                       T.OVERHEAD, V.STANDARD, tags=("travel",),
            description="Short-term vehicle rental for business use. Vans and commercial vehicles allow full VAT recovery. Car hire is subject to a 50% input VAT block if the car is available for any private use."),
    Account(7402, "Hotels",                         T.OVERHEAD, V.STANDARD, tags=("travel",),
            description="UK hotel accommodation is standard rated (20%). VAT reclaimable on business stays with a valid VAT invoice."),
    Account(7403, "U.K. Entertainment",             T.OVERHEAD, V.STANDARD, hmrc_box="CT600 Box 46", tags=("entertainment",),
            description="VAT on business entertainment is blocked from input tax recovery (HMRC VAT Notice 700/65). Disallowable for corporation tax - must be added back on CT600."),
    Account(7404, "Overseas Entertainment",         T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("entertainment",),
            description="Disallowable for corporation tax - must be added back on CT600."),
    Account(7405, "Overseas Travelling",            T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("travel",),
            description="Travel costs incurred outside the UK — international flights, foreign trains, overseas taxis. Outside scope of UK VAT as the place of supply is not the UK."),
    Account(7406, "Subsistence",                    T.OVERHEAD, V.STANDARD, tags=("travel",),
            description="Meals and refreshments during business travel. Standard rated with VAT reclaimable. Must be genuinely incurred away from the normal place of work — home-to-office meals are not deductible."),

    # Office & Admin
    Account(7500, "Printing",                       T.OVERHEAD, V.STANDARD, tags=("admin",),
            description="External printing costs — business cards, letterheads, brochures, and bulk print runs. Standard rated with VAT reclaimable on UK suppliers."),
    Account(7501, "Postage and Carriage",           T.OVERHEAD, V.EXEMPT,   tags=("admin",),
            description="Royal Mail universal service is VAT exempt. Private couriers (DHL, DPD, Hermes) are standard rated (20%). Default set to exempt as Royal Mail is most common; adjust per supplier."),
    Account(7502, "Office Stationery",              T.OVERHEAD, V.STANDARD, tags=("admin",),
            description="Paper, pens, envelopes, folders, printer ink, and general office supplies. Standard rated. VAT reclaimable on purchases from VAT-registered suppliers."),
    Account(7503, "Books etc.",                     T.OVERHEAD, V.ZERO,     tags=("admin",),
            description="Physical books, journals, newspapers, and maps are zero-rated. E-books and digital publications are also zero-rated since May 2020."),
    Account(7550, "Telephone and Fax",              T.OVERHEAD, V.STANDARD, tags=("comms",),
            description="Landline phone bills and line rental. Standard rated with VAT reclaimable. Private use on a business phone is a reportable benefit in kind unless strictly de minimis."),
    Account(7551, "Internet Charges",               T.OVERHEAD, V.STANDARD, tags=("comms",),
            description="Business broadband and data lines. Standard rated with VAT reclaimable. Apportion private use where the connection is shared (e.g. home offices)."),
    Account(7552, "Computers & Software",           T.OVERHEAD, V.STANDARD, tags=("tech",),
            description="Computer hardware and off-the-shelf software under the capitalisation threshold. Standard rated. Higher-value items are capitalised as fixed assets (code 30) with capital allowances."),
    Account(7553, "Mobile Charges",                 T.OVERHEAD, V.STANDARD, tags=("comms",),
            description="Business mobile phone bills and airtime. Standard rated with VAT reclaimable. Company-name contracts are exempt from the benefit-in-kind charge under Section 319 ITEPA 2003."),

    # Professional Fees
    Account(7600, "Legal Fees",                     T.OVERHEAD, V.STANDARD, tags=("professional",),
            description="Solicitor and barrister fees for business matters. Standard rated with VAT reclaimable on revenue-purpose fees. Legal fees on capital transactions (e.g. acquiring property or subsidiaries) are typically capitalised rather than expensed."),
    Account(7601, "Audit Fees",                     T.OVERHEAD, V.STANDARD, tags=("professional",),
            description="Statutory audit and assurance fees. Standard rated with VAT reclaimable. Typically accrued at year-end to match the period audited, not when invoiced."),
    Account(7602, "Accountancy Fees",               T.OVERHEAD, V.STANDARD, tags=("professional",),
            description="Bookkeeping, year-end accounts preparation, and corporation tax return work. Standard rated with VAT reclaimable. Personal tax work for directors is not deductible against company profits."),
    Account(7603, "Consultancy Fees",               T.OVERHEAD, V.STANDARD, tags=("professional",),
            description="External consultancy and advisory services. Standard rated with VAT reclaimable on UK providers. Non-UK providers may require reverse charge accounting under the general B2B rule."),
    Account(7604, "Professional Fees",              T.OVERHEAD, V.STANDARD, tags=("professional",),
            description="Fees for other regulated professionals — surveyors, architects, actuaries, valuers. Standard rated with VAT reclaimable. Capital-purpose fees should be capitalised rather than expensed."),
    Account(7605, "Management Charges Payable",     T.OVERHEAD, V.STANDARD,
            description="Inter-company management charges paid to parent or group companies. Standard rated where both entities are separately VAT-registered. A formal management services agreement should support the charge for transfer pricing purposes."),
    Account(7606, "Software Subscriptions",         T.OVERHEAD, V.STANDARD, tags=("tech",),
            description="SaaS and cloud software subscriptions (accounting software, CRM, productivity tools). Standard rated on UK suppliers. Non-UK suppliers require reverse charge accounting under B2B place-of-supply rules."),

    # Equipment
    Account(7700, "Equipment Hire",                 T.OVERHEAD, V.STANDARD,
            description="Short-term equipment rental (days to weeks). Standard rated with VAT reclaimable. Distinct from leasing (7702) which implies a longer-term arrangement."),
    Account(7701, "Office Machine Maintenance",     T.OVERHEAD, V.STANDARD,
            description="Service contracts and ad hoc repairs on office equipment — printers, copiers, phone systems, coffee machines. Standard rated with VAT reclaimable."),
    Account(7702, "Equipment Leasing",              T.OVERHEAD, V.STANDARD,
            description="Operating lease payments on business equipment under FRS 102. Standard rated with VAT reclaimable. IFRS 16 reporters capitalise the right-of-use asset on the balance sheet instead."),
    Account(7703, "Leasing Costs",                  T.OVERHEAD, V.STANDARD,
            description="Other lease-related costs — arrangement fees, documentation charges, early termination fees. Standard rated where a taxable supply exists. Capital elements may need separation."),

    # Premises Maintenance
    Account(7800, "Repairs and Renewals",           T.OVERHEAD, V.STANDARD, tags=("premises",),
            description="Routine repairs that restore an asset to its original condition. Standard rated and fully deductible. Improvements or enhancements are capital in nature and go to fixed assets instead."),
    Account(7801, "Cleaning",                       T.OVERHEAD, V.STANDARD, tags=("premises",),
            description="Office and premises cleaning — contract cleaners, window cleaning, waste removal. Standard rated with VAT reclaimable on business use."),
    Account(7802, "Laundry",                        T.OVERHEAD, V.STANDARD,
            description="Laundering of uniforms, linen, and workwear. Standard rated on commercial laundry services. Staff laundering their own workwear can claim a flat rate expense via self assessment."),
    Account(7803, "Premises Expenses",              T.OVERHEAD, V.STANDARD, tags=("premises",),
            description="Miscellaneous premises costs not covered by rent (7100), utilities (7200s), or maintenance (7800-7802). Standard rated by default. Use sparingly — prefer specific codes."),

    # Finance Costs
    Account(7900, "Bank Interest Paid",             T.OVERHEAD, V.EXEMPT,   hmrc_box="CT600 Box 44", tags=("finance",),
            description="Interest charged on business bank overdrafts and short-term facilities. VAT exempt as a financial service. Tax deductible as a trading expense on CT600 Box 44."),
    Account(7901, "Bank Charges",                   T.OVERHEAD, V.EXEMPT,   tags=("finance",),
            description="Account fees, transaction charges, and transfer costs. Generally VAT exempt as financial services. Some specific advisory or document services from banks may carry standard-rate VAT."),
    Account(7902, "Currency Charges",               T.OVERHEAD, V.EXEMPT,   tags=("finance",),
            description="Explicit foreign exchange conversion fees charged by banks or payment providers. VAT exempt as a financial service. Distinct from 7906 Exchange Rate Variance, which captures the FX gain/loss itself."),
    Account(7903, "Loan Interest Paid",             T.OVERHEAD, V.EXEMPT,   hmrc_box="CT600 Box 44", tags=("finance",),
            description="Interest on business loans from banks or third parties. VAT exempt. Deductible on CT600 Box 44, subject to the Corporate Interest Restriction for groups with net interest over £2 million."),
    Account(7904, "H.P. Interest",                  T.OVERHEAD, V.EXEMPT,   hmrc_box="CT600 Box 44", tags=("finance",),
            description="Interest element of hire purchase agreements. VAT exempt. Spread over the life of the agreement on an actuarial or sum-of-digits basis and deducted on CT600 Box 44."),
    Account(7905, "Credit Charges",                 T.OVERHEAD, V.EXEMPT,   tags=("finance",),
            description="Credit card merchant and processing fees charged for accepting card payments (e.g. Stripe, SumUp, Worldpay). VAT exempt as a financial service. Credit card interest on business cards should use 7907 Other Interest Charges instead."),
    Account(7906, "Exchange Rate Variance",         T.OVERHEAD, V.OUTSIDE_SCOPE, tags=("finance",),
            description="Realised and unrealised gains or losses on foreign currency transactions and balances. Outside scope of VAT. Taxable or deductible as a trading item when arising on trade receivables or payables."),
    Account(7907, "Other Interest Charges",         T.OVERHEAD, V.EXEMPT,   hmrc_box="CT600 Box 44", tags=("finance",),
            description="Interest on other borrowings not covered by 7900/7903/7904 — director loans, intercompany loans, lease interest. VAT exempt. Deductible on CT600 Box 44, subject to transfer pricing rules for related-party loans."),
    Account(7908, "Factoring Charges",              T.OVERHEAD, V.EXEMPT,   tags=("finance",),
            description="Fees paid to a factoring or invoice discounting company for advancing funds against trade receivables. VAT exempt as a financial service. With recourse factoring the credit risk remains with the business; non-recourse transfers the risk to the factor."),

    # Depreciation
    Account(8000, "Depreciation",                   T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Disallowable for corporation tax. Must be added back on CT600 - capital allowances are claimed instead."),
    Account(8001, "Plant/Machinery Depreciation",   T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Depreciation on plant, machinery, and production equipment. Disallowable for corporation tax — add back on CT600 Box 46 and claim Annual Investment Allowance or writing down allowances instead."),
    Account(8002, "Furniture/Fitting Depreciation",  T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Depreciation on office furniture, fittings, and shop fit-outs. Disallowable for corporation tax — add back on CT600 Box 46 and claim capital allowances instead."),
    Account(8003, "Vehicle Depreciation",           T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation", "motor"),
            description="Depreciation on company cars, vans, and commercial vehicles. Disallowable for corporation tax — add back on CT600 Box 46. Cars claim capital allowances based on CO2 emissions; vans may qualify for AIA."),
    Account(8004, "Office Equipment Depreciation",  T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 46", tags=("depreciation",),
            description="Depreciation on computers, printers, phones, and other office equipment. Disallowable for corporation tax — add back on CT600 Box 46 and claim Annual Investment Allowance instead."),

    # Other Overheads
    Account(8100, "Bad Debt Write Off",             T.OVERHEAD, V.OUTSIDE_SCOPE,
            description="Debts confirmed as uncollectable. VAT bad debt relief can be claimed if the debt is over 6 months old and has been written off. Claim via VAT Return Box 4."),
    Account(8102, "Bad Debt Provision",             T.OVERHEAD, V.OUTSIDE_SCOPE,
            description="Estimate of debts that may become uncollectable. Unlike write-offs, provisions are not eligible for VAT bad debt relief. Tax deduction only on actual write-off."),
    Account(8200, "Donations",                      T.OVERHEAD, V.OUTSIDE_SCOPE, hmrc_box="CT600 Box 47", tags=("charity",),
            description="Qualifying charitable donations are eligible for corporation tax relief under CT600 Box 47."),
    Account(8201, "Subscriptions",                  T.OVERHEAD, V.STANDARD,
            description="Professional body memberships, trade publications, and software subscriptions. VAT reclaimable where applicable."),
    Account(8202, "Clothing Costs",                 T.OVERHEAD, V.STANDARD,
            description="Uniforms, protective clothing, branded workwear. Everyday clothing is not deductible even if worn for work. Must be exclusively for business use."),
    Account(8203, "Training Costs",                 T.OVERHEAD, V.STANDARD,
            description="Staff training, CPD courses, professional development. VAT reclaimable on UK training providers. Must relate to the current trade to be tax deductible."),
    Account(8204, "Insurance",                      T.OVERHEAD, V.EXEMPT,   tags=("insurance",),
            description="General business insurance (professional indemnity, public liability, employer's liability). All VAT exempt — Insurance Premium Tax applies instead."),
    Account(8205, "Refreshments",                   T.OVERHEAD, V.STANDARD,
            description="Tea, coffee, biscuits for the office. VAT reclaimable as a business expense. Distinct from entertainment (7403) which is disallowable."),
    Account(8206, "Cash Register Discrepancies",    T.OVERHEAD, V.OUTSIDE_SCOPE,
            description="Differences between till readings and actual cash counted. Outside scope as no VAT supply is involved."),
    Account(8250, "Sundry Expenses",                T.OVERHEAD, V.STANDARD,
            description="Miscellaneous expenses that do not fit other categories. Keep usage minimal — categorise to specific codes where possible for better reporting."),

    # ── Tax & Control (9001-9999) ────────────────────────────────────
    Account(9001, "Taxation",                       T.TAX,     V.OUTSIDE_SCOPE, tags=("tax",),
            description="General taxation account for corporation tax charges. The P&L tax line. Distinct from the balance sheet liability (2110)."),
    Account(9998, "Suspense Account",               T.CONTROL, V.OUTSIDE_SCOPE, tags=("control",),
            description="Temporary holding account for transactions that cannot yet be classified. Must be cleared (allocated to correct accounts) before year-end."),
    Account(9999, "Mispostings Account",            T.CONTROL, V.OUTSIDE_SCOPE, tags=("control",),
            description="Correction account for entries posted to the wrong code. Journal the correction from here to the correct account. Must be zero at year-end."),
)
# fmt: on
