"""ClickHouse DDL, hierarchy dictionaries, and the canonical example queries.

The example-queries file matters as much as the DDL: it is where the dataset's traps are
made explicit. The group P&L MUST be summed as ``SUM(amount * weight_product)`` because
61 of the 531 US-GAAP arcs carry weight -1, and a plain ``SUM(amount)`` silently returns
a wrong number.
"""

from __future__ import annotations

from pathlib import Path

import polars as pl

_TYPE_MAP = {
    pl.Int8: "Int8", pl.Int16: "Int16", pl.Int32: "Int32", pl.Int64: "Int64",
    pl.UInt8: "UInt8", pl.UInt16: "UInt16", pl.UInt32: "UInt32", pl.UInt64: "UInt64",
    pl.Float32: "Float32", pl.Float64: "Float64",
    pl.Boolean: "Bool", pl.Utf8: "String", pl.Date: "Date", pl.Datetime: "DateTime",
}

# Tables that get a tuned MergeTree rather than the generic one.
_TABLE_ENGINES = {
    "fact_gl": {
        "partition_by": "(scenario_key, fiscal_year)",
        "order_by": "(entity, account_code, period_key)",
    },
    "fact_sales_lines": {
        "partition_by": "fiscal_year",
        "order_by": "(entity, period_key, customer_id, doc_no, line_no)",
    },
    "fact_drivers_units": {
        "partition_by": "fiscal_year",
        "order_by": "(entity, product_node_id, market_node_id, period_key)",
    },
    "fact_ic_transaction": {
        "partition_by": "fiscal_year",
        "order_by": "(flow_key, period_key, ic_txn_id)",
    },
    "fact_pnl": {
        "partition_by": "(scenario_type, fiscal_year)",
        "order_by": "(scenario_key, entity, period_no, group_account)",
    },
    "fact_elimination": {
        "partition_by": "fiscal_year",
        "order_by": "(account_code, period_key, ic_txn_id)",
    },
}


def _ch_type(dtype, nullable: bool = True) -> str:
    base = _TYPE_MAP.get(dtype)
    if base is None:
        for key, value in _TYPE_MAP.items():
            if dtype == key:
                base = value
                break
    base = base or "String"
    return f"Nullable({base})" if nullable and base != "String" else base


def write_clickhouse_ddl(dataset, output_dir: Path) -> Path:
    path = Path(output_dir) / "schema.sql"
    lines = [
        "-- Volteo Electronics Group - ClickHouse schema",
        "-- Generated by volteogen. Facts are MergeTree, partitioned so that a single",
        "-- scenario/fiscal-year slice can be dropped and rebuilt independently.",
        "",
        "CREATE DATABASE IF NOT EXISTS volteo;",
        "",
    ]

    for name, frame in sorted(dataset.tables.items()):
        engine = _TABLE_ENGINES.get(name)
        columns = []
        for column, dtype in zip(frame.columns, frame.dtypes):
            has_nulls = frame[column].null_count() > 0
            columns.append(f"    `{column}` {_ch_type(dtype, nullable=has_nulls)}")

        lines.append(f"CREATE TABLE IF NOT EXISTS volteo.{name}")
        lines.append("(")
        lines.append(",\n".join(columns))
        lines.append(")")
        if engine:
            lines.append("ENGINE = MergeTree")
            lines.append(f"PARTITION BY {engine['partition_by']}")
            lines.append(f"ORDER BY {engine['order_by']};")
        else:
            order = frame.columns[0]
            lines.append("ENGINE = MergeTree")
            lines.append(f"ORDER BY tuple(`{order}`);")
        lines.append("")

    # Hierarchy dictionaries: parent lookups for drill-up without a join.
    lines.append("-- Hierarchy dictionaries (parent lookup for fast drill-up)")
    for dim, table in (
        ("product", "dim_product_node"),
        ("market", "dim_market_node"),
        ("cost_center", "dim_cost_center_node"),
        ("profit_center", "dim_profit_center_node"),
    ):
        if table not in dataset.tables:
            continue
        lines.append(
            f"""CREATE DICTIONARY IF NOT EXISTS volteo.dict_{dim}_parent
(
    node_id String,
    parent_id String,
    name String,
    node_type String
)
PRIMARY KEY node_id
SOURCE(CLICKHOUSE(DB 'volteo' TABLE '{table}'))
LAYOUT(COMPLEX_KEY_HASHED())
LIFETIME(MIN 0 MAX 0);
"""
        )

    path.write_text("\n".join(lines))
    return path


def write_serving_views(dataset, output_dir: Path) -> Path:
    """Semantic views a BI tool points at directly.

    Everything a dashboard needs is here, so no statement logic, sign convention or
    line ordering ever gets re-implemented in the BI layer. Adding a report line is a
    YAML edit in config/reports/ — these views and the dashboards on top are untouched.
    """
    path = Path(output_dir) / "views.sql"
    path.write_text("""-- Volteo serving layer for BI tools. Run after schema.sql + load.sh.

-- ---------------------------------------------------------------------------
-- v_income_statement — THE view a dashboard binds to.
-- One row per (report line x entity x period). The report layout, the subtotal
-- composition and the sign convention all come from dim_report_line /
-- bridge_report_line, which are generated from config/reports/*.yaml.
-- A BI tool just picks: rows = label (sorted by sort_order), columns = entity,
-- value = sum(value). No custom SQL, no hardcoded lines.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW volteo.v_income_statement AS
SELECT
    l.report_id    AS report_id,
    l.sort_order   AS sort_order,
    l.label        AS label,
    l.indent       AS indent,
    l.is_subtotal  AS is_subtotal,
    f.entity       AS entity,
    f.scenario_key AS scenario_key,
    f.fiscal_year  AS fiscal_year,
    f.period_key   AS period_key,
    f.period_no    AS period_no,
    sum(f.amount_gc_actual_rates * b.weight) AS value,
    sum(f.amount_gc_budget_rates * b.weight) AS value_constant_fx
FROM volteo.fact_gl AS f
INNER JOIN volteo.bridge_report_line AS b ON b.account_class = f.account_class
INNER JOIN volteo.dim_report_line    AS l
        ON l.report_id = b.report_id AND l.line_id = b.line_id
GROUP BY l.report_id, l.sort_order, l.label, l.indent, l.is_subtotal,
         f.entity, f.scenario_key, f.fiscal_year, f.period_key, f.period_no;

-- ---------------------------------------------------------------------------
-- v_pnl_gaap — the same idea against the seeded US-GAAP tree, where the signed
-- weights are NOT all -1: 61 of the 531 arcs carry -1 and the rest +1.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW volteo.v_pnl_gaap AS
SELECT
    br.ancestor    AS gaap_concept,
    f.entity       AS entity,
    f.fiscal_year  AS fiscal_year,
    f.period_key   AS period_key,
    sum(f.amount_gc_actual_rates * br.weight_product) AS value
FROM volteo.fact_gl            AS f
INNER JOIN volteo.map_local_to_group AS m  ON m.local_account = f.account_code
INNER JOIN volteo.map_group_to_gaap  AS gg ON gg.group_account = m.group_account
INNER JOIN volteo.bridge_usgaap      AS br ON br.node = gg.gaap_concept
GROUP BY br.ancestor, f.entity, f.fiscal_year, f.period_key;

-- ---------------------------------------------------------------------------
-- v_revenue_detail — drill-through target. Sub-ledger grain: SKU, customer,
-- channel, market. Dimension labels are resolved here so the dashboard never
-- joins hierarchies by hand.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW volteo.v_revenue_detail AS
SELECT
    s.entity                  AS entity,
    s.fiscal_year             AS fiscal_year,
    s.period_key              AS period_key,
    s.doc_no                  AS doc_no,
    s.sku_code                AS sku_code,
    s.division_name           AS division_name,
    s.category_name           AS category_name,
    s.family_name             AS family_name,
    c.customer_name           AS customer_name,
    c.channel                 AS channel,
    c.customer_tier           AS customer_tier,
    mk.name                   AS market,
    mk.region                 AS region,
    s.qty                     AS qty,
    s.gross_amount            AS gross_amount,
    s.channel_discount_amount AS channel_discount_amount,
    s.invoiced_amount         AS invoiced_amount,
    s.std_cost_amount         AS std_cost_amount,
    s.invoiced_amount - s.std_cost_amount AS gross_profit,
    s.is_unassigned_product   AS is_unassigned_product
FROM volteo.fact_sales_lines  AS s
LEFT JOIN volteo.dim_customer    AS c  ON c.customer_id = s.customer_id
LEFT JOIN volteo.dim_market_node AS mk ON mk.node_id = s.market_node_id;

-- ---------------------------------------------------------------------------
-- v_cost_by_geo — opex by geography WITHOUT any geography column on the ledger.
--
-- The ledger carries only a cost centre; the cost-centre master carries site,
-- country, geo_region and the market it supports. Two different geographies, both
-- real: `geo_region` is where the cost was INCURRED, `serves_region` is the market it
-- SUPPORTS. A German sales team serving all of EMEA differs on the two.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW volteo.v_cost_by_geo AS
SELECT
    f.entity                AS entity,
    f.fiscal_year           AS fiscal_year,
    f.period_key            AS period_key,
    f.account_class         AS account_class,
    cc.site                 AS site,
    cc.site_city            AS site_city,
    cc.country              AS country,
    cc.geo_region           AS incurred_region,
    cc.function             AS function,
    cc.name                 AS cost_center,
    sm.name                 AS serves_market,
    if(empty(ifNull(sm.region, '')), 'ALL', sm.region) AS serves_region,
    cc.home_profit_center   AS home_profit_center,
    sum(f.amount_gc_actual_rates) AS amount
FROM volteo.fact_gl AS f
INNER JOIN volteo.dim_cost_center_node AS cc ON cc.node_id = f.cost_center_node_id
LEFT  JOIN volteo.dim_market_node      AS sm ON sm.node_id = cc.serves_market_node_id
GROUP BY entity, fiscal_year, period_key, account_class, site, site_city, country,
         incurred_region, function, cost_center, serves_market, serves_region,
         home_profit_center;

-- ---------------------------------------------------------------------------
-- v_data_quality — the defects, surfaced as a monitorable table rather than
-- buried in a README. Point an alert at it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW volteo.v_data_quality AS
SELECT 'untagged_product' AS issue, entity, fiscal_year, period_key,
       count() AS rows_affected, sum(abs(amount_gc_actual_rates)) AS amount
FROM volteo.fact_gl WHERE product_node_id = 'UNASSIGNED'
GROUP BY entity, fiscal_year, period_key
UNION ALL
-- Only the two LOCAL legs of a flow are expected to carry a partner. Elimination and
-- substitution rows have none by nature, so including them would drown the real defect.
SELECT 'ic_partner_missing', entity, fiscal_year, period_key,
       count(), sum(abs(amount_gc_actual_rates))
FROM volteo.fact_gl
WHERE ic_leg IN ('seller', 'buyer')
  AND ic_partner = '~NA~'
  AND entity NOT IN ('ELIM', 'GRP')
GROUP BY entity, fiscal_year, period_key;
""")
    return path


def write_load_script(dataset, output_dir: Path) -> Path:
    """Parquet -> ClickHouse. Idempotent, no per-table hand-written SQL."""
    path = Path(output_dir) / "load.sh"
    tables = sorted(dataset.tables)
    path.write_text("""#!/usr/bin/env bash
# Load the generated Parquet files into ClickHouse.
#   ./load.sh [parquet_dir] [clickhouse-client args...]
set -euo pipefail
DIR="${1:-../parquet}"; shift || true
CH="$(command -v clickhouse-client >/dev/null && echo clickhouse-client || echo 'clickhouse client') ${*:-}"

$CH --queries-file schema.sql
for f in "$DIR"/*.parquet; do
  t=$(basename "$f" .parquet)
  echo "  loading $t"
  $CH --query "TRUNCATE TABLE IF EXISTS volteo.$t"
  $CH --query "INSERT INTO volteo.$t FORMAT Parquet" < "$f"
done
$CH --queries-file views.sql
echo "Loaded ${#}: $(basename "$DIR") -> volteo.*"
""")
    path.chmod(0o755)
    del tables
    return path


def write_example_queries(dataset, output_dir: Path) -> Path:
    path = Path(output_dir) / "example_queries.sql"
    content = """-- Volteo Electronics Group - canonical queries
-- Every query here encodes a rule the dataset will punish you for ignoring.

-- ============================================================================
-- 1. GROUP P&L BY US-GAAP VIEW  *** READ THIS ONE ***
-- ----------------------------------------------------------------------------
-- 61 of the 531 US-GAAP calculation arcs carry weight -1. A plain SUM(amount)
-- over a roll-up therefore returns a WRONG number that still looks plausible.
-- The bridge pre-multiplies weights down each path, so the correct aggregation
-- is always SUM(amount * weight_product).
-- ============================================================================
SELECT
    b.ancestor                                AS gaap_concept,
    SUM(g.amount_gc_actual_rates * b.weight_product) AS amount_usd
FROM volteo.fact_gl                AS g
JOIN volteo.map_local_to_group     AS m  ON m.local_account = g.account_code
JOIN volteo.map_group_to_gaap      AS gg ON gg.group_account = m.group_account
JOIN volteo.bridge_usgaap          AS b  ON b.node = gg.gaap_concept
WHERE g.scenario_key = 'ACT'
  AND g.fiscal_year  = 2025
GROUP BY b.ancestor
ORDER BY amount_usd;

-- ============================================================================
-- 2. THE BY-NATURE -> BY-FUNCTION PIVOT
-- The SAME salary account becomes "COGS - labour", "R&D" or "G&A" depending only
-- on the FUNCTION of the cost centre it was posted to.
-- ============================================================================
SELECT
    mm.management_line,
    SUM(g.amount_gc_actual_rates) AS amount_usd
FROM volteo.fact_gl              AS g
JOIN volteo.dim_cost_center_node AS cc ON cc.node_id = g.cost_center_node_id
JOIN volteo.map_local_to_group   AS m  ON m.local_account = g.account_code
JOIN volteo.map_management       AS mm
       ON mm.group_account = m.group_account
      AND (mm.cc_function = cc.function OR mm.cc_function = '~ANY~')
WHERE g.scenario_key = 'ACT'
  AND mm.is_excluded = false      -- interest and tax have NO management line: the
GROUP BY mm.management_line       -- management P&L deliberately stops at EBIT
ORDER BY amount_usd DESC;

-- ============================================================================
-- 3. DRILL-THROUGH: GL revenue -> the sub-ledger behind it
-- GL carries product at FAMILY grain; SKU and customer detail exist ONLY in the
-- sub-ledger. The two tie exactly (validator V7).
-- ============================================================================
SELECT
    s.sku_code,
    s.customer_id,
    s.channel,
    SUM(s.qty)              AS units,
    SUM(s.invoiced_amount)  AS invoiced
FROM volteo.fact_sales_lines AS s
WHERE s.entity      = 'DE01'
  AND s.period_key  = '2024-11'         -- P05: the Black Friday peak
GROUP BY s.sku_code, s.customer_id, s.channel
ORDER BY invoiced DESC
LIMIT 50;

-- ============================================================================
-- 4. INTERCOMPANY CHECK: both legs come from ONE record, so they must net to 0
-- Anything left over is either a registered defect or a real break.
-- ============================================================================
SELECT
    t.flow_key,
    t.period_key,
    SUM(CASE WHEN g.ic_leg = 'seller' THEN g.amount_gc_actual_rates ELSE 0 END) AS seller_leg,
    SUM(CASE WHEN g.ic_leg = 'buyer'  THEN g.amount_gc_actual_rates ELSE 0 END) AS buyer_leg,
    SUM(CASE WHEN g.ic_leg IN ('seller','buyer') THEN g.amount_gc_actual_rates ELSE 0 END) AS net
FROM volteo.fact_ic_transaction AS t
JOIN volteo.fact_gl             AS g ON g.ic_txn_id = t.ic_txn_id
GROUP BY t.flow_key, t.period_key
HAVING abs(net) > 0.02              -- expect exactly ONE row: the 1.3% DE->ES defect
ORDER BY abs(net) DESC;

-- ============================================================================
-- 5. GROSS-TO-NET WATERFALL
-- In electronics the gap is large and made of four named components, each on its
-- own account. "Revenue" without saying gross or net is a meaningless number.
-- ============================================================================
SELECT
    entity,
    fiscal_year,
    SUM(gross_revenue)     AS gross,
    SUM(channel_discounts) AS channel_discounts,
    SUM(volume_rebate)     AS volume_rebate,
    SUM(mdf)               AS mdf,
    SUM(returns_reserve)   AS returns_reserve,
    SUM(price_protection)  AS price_protection,
    SUM(net_revenue)       AS net
FROM volteo.rpt_gross_to_net AS w
JOIN volteo.dim_calendar     AS c USING (period_key)
GROUP BY entity, fiscal_year
ORDER BY entity, fiscal_year;

-- ============================================================================
-- 6. THE THREE DIMENSION STATES  (spec 5)
-- '~NA~'       = structurally not applicable (payroll has no product). CORRECT.
-- 'UNASSIGNED' = should have been tagged but was not. A DEFECT.
-- anything else = a real member.
-- Treating '~NA~' and 'UNASSIGNED' alike is the single easiest way to get a
-- wrong answer from this dataset.
-- ============================================================================
SELECT
    account_class,
    countIf(product_node_id = '~NA~')       AS structurally_na,
    countIf(product_node_id = 'UNASSIGNED') AS untagged_defect,
    countIf(product_node_id NOT IN ('~NA~','UNASSIGNED')) AS tagged
FROM volteo.fact_gl
GROUP BY account_class
ORDER BY account_class;

-- ============================================================================
-- 7. CONSTANT CURRENCY: how much of "growth" was actually FX?
-- ============================================================================
SELECT
    entity,
    fiscal_year,
    SUM(amount_gc_actual_rates) AS at_actual_rates,
    SUM(amount_gc_budget_rates) AS at_budget_rates,
    SUM(amount_gc_actual_rates) - SUM(amount_gc_budget_rates) AS fx_effect
FROM volteo.fact_gl
WHERE account_class = 'revenue_trade'
GROUP BY entity, fiscal_year
ORDER BY entity, fiscal_year;

-- ============================================================================
-- 8. COST-CENTRE REORGANISATION: facts keep the ORIGINAL cost centre forever.
-- Restating history onto the new org requires dim_cost_center_version. Reports
-- that skip it silently compare a merged department against its unmerged self.
-- ============================================================================
SELECT
    v.cc_hierarchy_version,
    v.restated_node_id,
    SUM(g.amount_gc_actual_rates) AS amount
FROM volteo.fact_gl                 AS g
JOIN volteo.dim_cost_center_version AS v
       ON v.node_id = g.cost_center_node_id
      AND v.fiscal_year = g.fiscal_year
WHERE g.account_class = 'payroll'
GROUP BY v.cc_hierarchy_version, v.restated_node_id
ORDER BY v.cc_hierarchy_version, amount DESC;
"""
    path.write_text(content)
    return path
